stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - params.yaml
    outs:
      - data/raw
  data_processing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - data/raw
      - src/data/data_preprocessing.py
      - params.yaml
    outs:
      - data/interim
  feature_enginearing:
    cmd: python src/features/feature_engineering.py
    deps:
      - data/interim
      - params.yaml
      - src/features/feature_engineering.py
    outs:
      - data/processed
      - models/vectorizer.pkl
  model_building:
    cmd: python src/model/model_building.py
    deps:
      - data/processed
      - params.yaml
      - src/model/model_building.py
    outs:
      - models/model.pkl
  model_evaluations:
    cmd: python src/model/model_evaluations.py
    deps:
      - src/model/model_evaluations.py
      - models/model.pkl
      - params.yaml
    outs:
      - reports/experiment_info.json
      - reports/metrics.json
  register_model:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py
      - reports/experiment_info.json
      - reports/metrics.json

    